a = input('Digite algo:')
print ('O tipo primitivo desse valor e:')
print ('So tem espacos?', a.isspace())
print ('E um numero?', a.isnumeric())
print ('E alfabetico?' , a.isalpha())
print ('E alfanumerico?', a.isalnum())
print ('Esta em maiusculo?', a.isupper())
print ('Esta em minusculas?', a.islower())
