print('ola mundo')
print (7+4)
print('ola' , 5)
nome = ("vitoria")
idade = (16)
peso = (65.5)
print (nome , idade , peso)
nome = input ('qual o seu nome?')
idade = input ('qual a sua idade ?')
peso = input ('qual o seu peso ?')
print (nome , idade , peso )
print ('ola vitoria! seja bem vinda')
dia = input ('que dia voce nasceu?')
mes = input ('que mes voce nasceu?')
ano = input ('que ano voce nasceu ?')
print (dia , mes , ano)
numero1=int(input('digite um numero inteiro'))
numero2=int(input('digite um numero inteiro'))
soma = numero1+numero2
print (soma)