#Faça um programador que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informaçoes possiveis sobre ele.
a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ',a.isspace())
print('É um numero? ' ,a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Esta em minusculas? ',a.isupper())
print('Esta em minusculas? ',a.islower())
print('Esta capitalizada? ', a.istitle())
