nome = str(input('digite seu nome completo:')).strip()
nome = nome.split()
print('muito prazer em te conhecer!')
print('seu primeiro nome é {}'.format(nome[0]))
print(' seu ultimo nome é {}'.format(nome[len(nome)-1]))
