nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print(f'Seu nome em letras maiusculas é {nome.upper()}')
print(f'Seu nome em letras minusculas é {nome.lower()}')
espaços = (nome.count(' '))
print(f'Seu nome ao todo tem {len(nome) - espaços}letras')
print(f'Seu primeiro nome tem {nome.find(' ')}letras')
