n = input('Digite algo: ')

print ('O tipo primitivo é:', type(n))
print ('Só tem espaços? ', (n.isspace()))
print ('É numérico? ', (n.isnumeric()))
print ('É alfabético? ', (n.isalpha()))
print ('É alfanumérico? ', (n.isalnum()))
print ('Está em letras maiúsculas? ', (n.isupper()))
print ('Está em letras minúsculas? ', (n.islower()))
print ('Está capitalizada?', (n.istitle()))
