ti = ("Palmeiras", "Flamengo", "Fluminense", "São Paulo", "Bahia", "Athletico-PR", "Botafogo", "Coritiba", "Vasco da Gama", "Vitória", "Internacional", "Goiás", "Santos", "Ceará", "Corinthians", "Grêmio", "Cruzeiro", "Remo", "Chapecoense", "Mirassol")
print("-"*20)
print(f"Lista de times do brasileirão 2026: {ti}")
print("-"*20)
print(f"Os primeiros 5 são: {ti[:5]}")
print("-"*20)
print(f"Os 4 ultimos são: {ti[-4:]}")
print("-"*20)
print(f"Os times em ordem alfabetica é: {sorted(ti)}")