n = str(input('digite seu nome completo: '))
nome = n.split()
print('muito prazer em te conhecer!')
print("seu primeiro nome é {} ".format(nome[0]))
print('seu último nome é {}'.format(nome[len(nome)-1]))
